import AppKit
import SpinnetCore

/// Only the Host polls NSPasteboard. No Plugin process participates in collection.
final class ClipboardCollector {
    private let store: ClipboardHistoryStore
    private var timer: Timer?
    private var lastChangeCount: Int?
    private var reportedFailure = false
    private let changeCount: () -> Int
    private let readContent: () -> ClipboardContent?
    private let sourceApplication: () -> (name: String, bundleID: String)
    var onError: ((Error) -> Void)?

    init(store: ClipboardHistoryStore,
         changeCount: @escaping () -> Int = { NSPasteboard.general.changeCount },
         readContent: @escaping () -> ClipboardContent? = { ClipboardCollector.readCurrent() },
         sourceApplication: @escaping () -> (name: String, bundleID: String) = {
             let app = NSWorkspace.shared.frontmostApplication
             return (app?.localizedName ?? "Unknown application", app?.bundleIdentifier ?? "")
         }) {
        self.store = store
        self.changeCount = changeCount
        self.readContent = readContent
        self.sourceApplication = sourceApplication
    }
    deinit { timer?.invalidate() }

    func start() throws {
        try resetBaseline()
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            guard let self else { return }
            do { try self.poll(); self.reportedFailure = false }
            catch {
                if !self.reportedFailure { self.reportedFailure = true; self.onError?(error) }
            }
        }
    }

    func resetBaseline() throws {
        let count = changeCount()
        try store.observe(changeCount: count, content: nil, sourceName: "", sourceBundleID: "")
        lastChangeCount = count
    }

    func poll() throws {
        let count = changeCount()
        let settings = store.settings
        let shouldRead = settings.enabled && !settings.paused && count != lastChangeCount
        let content = shouldRead ? readContent() : nil
        guard changeCount() == count else { return }
        let app = sourceApplication()
        try store.observe(changeCount: count,
            content: content,
            sourceName: app.name,
            sourceBundleID: app.bundleID)
        lastChangeCount = count
    }

    static func readCurrent(from board: NSPasteboard = .general) -> ClipboardContent? {
        let excluded = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]
        guard board.types?.contains(.fileURL) != true, !excluded.contains(where: { board.types?.contains(NSPasteboard.PasteboardType($0)) == true }) else { return nil }
        if let url = board.string(forType: .URL), URL(string: url)?.scheme != "file" {
            return ClipboardContent(text: url, type: .url)
        }
        guard let text = board.string(forType: .string) else { return nil }
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        let isURL = URL(string: trimmed).map { ["http", "https"].contains($0.scheme?.lowercased() ?? "") && $0.host != nil && !trimmed.contains(where: \.isWhitespace) } ?? false
        return ClipboardContent(text: text, type: isURL ? .url : .text)
    }
}
